# Generated by Django 3.0.6 on 2020-05-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_public',
        ),
    ]
