# Generated by Django 3.0.6 on 2020-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200506_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='weather',
            field=models.CharField(choices=[('🌞', 'sunny'), ('🌥', 'cloudy'), ('🌧', 'raining')], default='sunny', max_length=50),
        ),
    ]
